# Generated by Selenium IDE
from model.group import Group


def test_add_group(app):
    app.group.create(Group(name="test1", header="werwegw", footer="qweqwe"))


def test_add_empty_group(app):
    app.group.create(Group(name="", header="", footer=""))
